### ISSUE TITLE
[Typo]: Table of content mistakes on Functional Specification

### ISSUE THREAD

**Issue by laurentbouquin** [algosup/2023-2024-project-3-virtual-processor-team-8#3]
### Which document is concerned?

The Functional-Specification.md

### What is the typo?

In the B2 part, "loss condition" should have an 's' at the end.
In the C1 part, there should be spaces before and after /.

### priority

Should be done quickly

**Comment by Ianlaur** [comment]
I'm going to ask you to be a little more specific in your remarks.
It's hard to know what the overall problem is with the description of the issue, plus the "should have an 's' at the end." explanation, a little more precision is required on "On what commit was the issue made on", "What line of code is the issue on?",  etc....
Otherwise the corrections have been made.
